### PR TITLE
add optional CI user

### PR DESCRIPTION
**Pull request by willingham**
This PR adds the code necessary to create an IAM user that has permissions to upload to the S3 origin bucket and create invalidations on the CloudFront Distribution.  Creation of this user is determined by an optional input variable, `create_ci_user`.

This PR has no breaking changes.

### CODE REVIEW

**Review by joseph-wortmann — COMMENTED** [review]
Minor thing, but would you mind cleaning up the spacing? You know how OCD I can be :)

**Review by joseph-wortmann — CHANGES_REQUESTED** [review]
Actually, upon further reflection - I think that I would rather see this handled through the creation of a role in the module, and an output of that role's arn. The role would always be created. Then you can add this capability to any user, group, etc. that you want. Can you make that change?

**Comment by willingham** [comment]
That seems like a good solution.  I'll do that.

**Comment by willingham** [comment]
I made the changes.  Let me know what you think.

**Review by joseph-wortmann — CHANGES_REQUESTED** [review]
Hi Thomas. I apologize, my head hasn't been in this.

I need two more changes, then we should be good to go. First, remove the role. On further reflection, roles are a bit limiting. All we really need is the managed IAM policy.

For that, please do the policy document using the data source `aws_iam_policy_document` to create it. This will make it a two item creation.

Name the managed policy so that it is obvious which cloudfront distribution it is managing. Maybe use the distro name as a prefix?

Please limit what the policy can do to the bucket and it's resources. I think that you just want put/get/delete, right? What you have now allows the maintainer to alter access rights, make the bucket public, other really bad stuff, etc.

Then pass the ARN and the id for the managed policy as outputs.

Thank you, and sorry once again for the back and forth!

-Joe

**Comment by willingham** [comment]
No worries! I know you're busy.  I'll make the changes and ping you again.

**Comment by willingham** [comment]
Hey Joe,

I updated the code.  Let me know what you think.  If you still want me to remove more of the s3 permissions, just let me know.

Thomas

**Review by joseph-wortmann — CHANGES_REQUESTED** [review]
Thomas - sorry this took so long for me to review.

Two additional changes:
1 - please change the 'ci' names to to something like 'manage', as this policy can be used for more than just CI.
2 - update 'outputs.tf` to output the arn of the new policy you have created, so that it is easily accessible outside the module

**Comment by willingham** [comment]
No worries!  I think I've got those changes done now.

**Review by joseph-wortmann — APPROVED** [review]

**Pull request merged**
